version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: backend
    container_name: backend
    expose:
      - "6000"  # internal port only
    restart: unless-stopped
    networks:
      - webnet

  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy  # waits for backend healthcheck
    restart: unless-stopped
    networks:
      - webnet
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro  # optional for per-site configs

networks:
  webnet:
    driver: bridge
